### Configurações Globais
@baseUrl = http://localhost:3000
@contentType = application/json

### ----------------------------------------------------
### AUTENTICAÇÃO
### ----------------------------------------------------

# @name requisicaoLogin
# Realizar login para obter o token do administrador inicial
POST {{baseUrl}}/usuarios/login
Content-Type: {{contentType}}

{
    "email": "admin@locus.com",
    "senha_hash": "LocusAdmin"
}

### ----------------------------------------------------
### CONFIGURAÇÃO DO TOKEN AUTOMÁTICO
### ----------------------------------------------------

# Pega automaticamente o token retornado pela requisição acima
@token = {{requisicaoLogin.response.body.token}}


### ----------------------------------------------------
### ROTAS PÚBLICAS DE INSTITUIÇÕES
### ----------------------------------------------------

# Listar todas as instituições
GET {{baseUrl}}/instituicoes

###

# Buscar instituição por ID
GET {{baseUrl}}/instituicoes/1

###

# Buscar instituição por Nome
GET {{baseUrl}}/instituicoes/nome/Universidade Locus do Brasil

###

# Buscar instituições por Cidade
GET {{baseUrl}}/instituicoes/cidade/Porto Alegre


### ----------------------------------------------------
### ROTAS PROTEGIDAS (REQUEREM TOKEN ADMIN)
### ----------------------------------------------------

# Criar nova instituição
POST {{baseUrl}}/instituicoes
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "nome": "Instituto Tecnológico Locus",
  "rua": "Avenida da Inovação",
  "numero": "500",
  "bairro": "Distrito Industrial",
  "cidade": "Porto Alegre",
  "estado": "RS",
  "cep": "90000000",
  "telefone": "5132109876"
}

###

# Atualizar dados da instituição
PUT {{baseUrl}}/instituicoes/2
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "nome": "Instituto Locus - Nome Atualizado",
  "telefone": "51988887777"
}

###

# Deletar registro de instituição
DELETE {{baseUrl}}/instituicoes/2
Authorization: Bearer {{token}}